version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: homesweet-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homesweet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - homesweet-network

  redis:
    image: redis:7.2
    container_name: homesweet-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - homesweet-network

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - homesweet-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    restart: always
    command:
      - "--mysqld.username=exporter:testpassword"
      - "--mysqld.address=homesweet-db:3306"
    ports:
      - "9104:9104"
    networks:
      - homesweet-network

  ### Elasticsearch
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - homesweet-network

  ### Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - homesweet-network

  ### Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - homesweet-network

networks:
  homesweet-network:
    driver: bridge

volumes:
  mysqldata:
  redisdata:
  es_data: