version: '3.9'
services:
  spring:
    image: homesweet-backend
    container_name: homesweet-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - homesweet-network
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: homesweet-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homesweet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - homesweet-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    restart: always
    command:
      - "--mysqld.username=exporter:testpassword"
      - "--mysqld.address=homesweet-db:3306"
    ports:
      - "9104:9104"
    networks:
      - homesweet-network


networks:
  homesweet-network:
    driver: bridge
volumes:
  mysqldata: