version: '3.9'

services:
  spring:
    image: homesweet-backend
    container_name: homesweet-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis                 # Redis Host 연결
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - homesweet-network
    restart: always
    mem_limit: 1024m

  redis:
    image: redis:7.2
    container_name: homesweet-redis
    restart: always
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - homesweet-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    restart: always
    command:
      - "--mysqld.username=${DATABASE_USERNAME}:${DATABASE_PASSWORD}"
      - "--mysqld.address=${DATABASE_HOST}:3306"
    ports:
      - "9104:9104"
    networks:
      - homesweet-network

networks:
  homesweet-network:
    driver: bridge

volumes:
  redisdata: