server:
  port: 8080

spring:
  application:
    name: homesweet-back
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  flyway:
    enabled: false
  # sql:
  #   init:
  #     mode: always
  #     schema-locations: classpath:db/schema.sql
  #     data-locations: classpath:db/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id

logging:
  level:
    com.homesweet.homesweetback: INFO
    org.springframework.security: DEBUG

# JWT 개발 환경 설정
jwt:
  secret: ${JWT_SECRET:homesweet-back-jwt-secret-key-for-test-only}
  access-token-expiration: 18000000   # 5시간
  refresh-token-expiration: 604800000 # 7일 

# OAuth2 개발 환경 설정
app:
  oauth2:
    redirect-uri: http://localhost:3000/login/callback
    redirect-uri-on-register: http://localhost:3000/signup/callback
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000