input {
  jdbc {
    jdbc_connection_string => "jdbc:mysql://localhost:3307/small_db?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true"
    jdbc_user => "root"
    jdbc_password => "root"

    jdbc_driver_library => "/Users/junnukim1007gmail.com/IdeaProjects/homesweet-back/logstash/mysql-connector-java-8.0.28.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"

    jdbc_fetch_size => 1000
    jdbc_page_size  => 1000

    use_column_value => true
    tracking_column  => "chatroom_id"
    record_last_run  => true
    last_run_metadata_path => "/Users/junnukim1007gmail.com/IdeaProjects/homesweet-back/logstash/.logstash_chatroom_last_run"

    statement => "
      SELECT
          cr.room_id AS chatroom_id,
          cr.name AS chatroom_name,
          cr.thumbnail_url AS thumbnail_url,
          cr.is_deleted AS is_deleted,
          cr.created_at AS created_at
      FROM chat_room cr
      WHERE cr.room_id > :sql_last_value
      ORDER BY cr.room_id
      LIMIT 100000
    "

    schedule => "*/30 * * * * *"
  }
}

filter {
  mutate {
    convert => {
      "chatroom_id" => "integer"
      "is_deleted"  => "boolean"
    }
  }
  mutate {
    remove_field => ["@version", "@timestamp"]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "chatroom"
    document_id => "%{chatroom_id}"
  }
  stdout { codec => json_lines }
}