input {
  kafka {
    bootstrap_servers => ["kafka:29092"]
    topics => ["user-access-log"]
    group_id => "logstash-consumer"
    auto_offset_reset => "latest"
  }
}

filter {
  json { source => "message" }
  mutate {
    convert => {
      "executionTime" => "integer"
    }
  }
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "user-access-log-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}