input {
  jdbc {
    jdbc_connection_string => "jdbc:mysql://localhost:3307/small_db?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true"
    jdbc_user => "root"
    jdbc_password => "root"

    jdbc_driver_library => "/Users/junnukim1007gmail.com/IdeaProjects/homesweet-back/logstash/mysql-connector-java-8.0.28.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"

    # 메모리 최적화
    jdbc_fetch_size => 1000
    jdbc_page_size  => 1000

    # incremental load
    use_column_value => true
    tracking_column  => "product_id"
    record_last_run  => true
    last_run_metadata_path => "/Users/junnukim1007gmail.com/IdeaProjects/homesweet-back/logstash/.logstash_jdbc_last_run"

    # SQL (리뷰 평균 + 개수 포함)
    statement => "
      SELECT
          p.product_id,
          p.category_id,
          p.user_id AS seller_id,
          p.name,
          p.image_url,
          p.brand,
          p.base_price,
          p.discount_rate,
          p.shipping_price,
          p.status,
          p.description,

          c.name AS category_name,

          -- 평균 평점
          (
              SELECT COALESCE(AVG(r.rating), 0)
              FROM products_reviews r
              WHERE r.product_id = p.product_id
          ) AS average_rating,

          -- 리뷰 개수
          (
              SELECT COALESCE(COUNT(r2.review_id), 0)
              FROM products_reviews r2
              WHERE r2.product_id = p.product_id
          ) AS review_count,

          p.created_at,
          p.updated_at
      FROM products p
      JOIN product_category c
        ON p.category_id = c.category_id
      WHERE p.product_id > :sql_last_value
      ORDER BY p.product_id
      LIMIT 100000
    "

    # 30초마다 업데이트
    schedule => "*/30 * * * * *"
  }
}

filter {
  # 타입 변환
  mutate {
    convert => {
      "product_id"      => "integer"
      "category_id"     => "integer"
      "seller_id"       => "integer"
      "base_price"      => "integer"
      "shipping_price"  => "integer"
      "discount_rate"   => "float"
      "average_rating"  => "float"
      "review_count"    => "integer"
    }
  }

  # 불필요 필드 제거
  mutate {
    remove_field => ["@version", "@timestamp"]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "products"
    document_id => "%{product_id}"
  }

  stdout {
    codec => json_lines
  }
}